require('../scss/main.scss');
require('./utils')
require('./main');
require('./theme_setup');
require('./fonts/icon.font');
require('./header')
require('./scroll-to-top');
require('select2/dist/js/select2.js');
require('./language-switcher');
